/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./src/components/icons/ArrowLeft.vue')['default']
    CarOutline: typeof import('./src/components/icons/CarOutline.vue')['default']
    DepartmentOption: typeof import('./src/components/DepartmentOption.vue')['default']
    DirectionsWalkOutlined: typeof import('./src/components/icons/DirectionsWalkOutlined.vue')['default']
    FiltersMenu: typeof import('./src/components/FiltersMenu.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NearMeLocation: typeof import('./src/components/icons/NearMeLocation.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    OptionsOutlined: typeof import('./src/components/icons/OptionsOutlined.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    ShareLocation: typeof import('./src/components/icons/ShareLocation.vue')['default']
  }
}
