version: '3.1'
services:
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: flints
      MONGO_INITDB_ROOT_PASSWORD: moretechababa
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017